### ISSUE TITLE
Feed Back

### ISSUE THREAD

**Issue by Charlie-robin** [Roscoe00/calculator#4]
# Feedback

Hey Charlie here, feel free to message me on Slack if you want any clarification on the points below. I will give you both positive and constructive feedback on your project.

## Site

- The calculator looks good on a large desktop. You can see the numbers and operators clearly and when you are going to interact with them the hover is a nice effect.

- The project is not responsive though and hasn't been design mobile first. With the next project give this a go. It will boost you confidence with media queries and using dev tools.

- The theme / colors match your background image which is a great idea for little projects. Pick a theme and run with it which you have, it is awesome.

- It is good to have a README.md it is a good practice to create these so keep it up. To have your thought process / psuedo-code documented will help you get better at breaking problems down and solving them.

  - I would recommend just polishing it up a little bit. Have a look at this [example](https://github.com/alessandrothedev/calculator). Alessandro went to town on his.
  - Markdown is great and worth 10mins of your time. [Basic md syntax](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

- The Calculator functions which is great, good going! You have added lots of nice features to it.

  - Adding the logic to only allow one decimal and operator was a nice touch and can catch people out.
  - The positive-negative button is cool.
  - Wrapping large numbers is great.

- Try dividing a value by 0 and see what you get.

---

## Code

- This is 100% extra but I think you'll like it. With SCSS you can use a for loop, its a (@for)[https://sass-lang.com/documentation/at-rules/control/for]. This means you could condense your button / grid area declarations. See below. The commented out code can be replaced with the `@for` as it is doing the same thing.

```scss
// _grid.scss

@for $index from 0 through 9 {
  #button__#{$index} {
    grid-area: key-$index;
  }
}

//  #buttons__0 {
//     grid-area: key-0;
//  }
//  #buttons__1 {
//     grid-area: key-1;
//  }

//  #buttons__2 {
//     grid-area: key-2;
//  }

//  #buttons__3 {
//     grid-area: key-3;
//  }

//  #buttons__4 {
//     grid-area: key-4;
//  }

//  #buttons__5 {
//     grid-area: key-5;
//  }

//  #buttons__6 {
//     grid-area: key-6;
//  }

//  #buttons__7 {
//     grid-area: key-7;
//  }

//  #buttons__8 {
//     grid-area: key-8;
//  }

//  #buttons__9 {
//     grid-area: key-9;
//  }
```

- With your JS it is very well organized and documented. This will help you in a couple of weeks when you come back to these projects.

- With JS when naming variables they generally are camelCased. BEM naming your variables is not a good idea, BEM is for styling, camelCasing for JS. You will need to rename your variables e.g. `key__decimal` will need to be `keyDecimal`.

- You are not using helper functions. It would be a good refactoring exercise to see where you repeat things and turn them into functions.

```js
// calculator.js

for (let i = 0; i < number.length; i++) {
  number[i].addEventListener("click", () => {
    // THIS BLOCK BELOW IS SIMILAR
    mainDisplay = `${mainDisplay}` + `${number[i].innerHTML}`;
    finalDisplay.innerHTML = `${mainDisplay}`;
    subDisplay = `${subDisplay}` + `${number[i].innerHTML}`;
    workingDisplay.innerHTML = `${subDisplay}`;
  });
}

// ==========================
// ====decimal and minus=====
// ==========================

key__decimal.addEventListener("click", () => {
  if (mainDisplay.includes(".")) {
  } else {
    // TO THIS BLOCK
    mainDisplay = `${mainDisplay}` + `${key__decimal.innerHTML}`;
    finalDisplay.innerHTML = `${mainDisplay}`;
    subDisplay = `${subDisplay}` + `${key__decimal.innerHTML}`;
    workingDisplay.innerHTML = `${subDisplay}`;
  }
});
```

could be.

```js
// calculator.js

const updateDisplay = HTMLElement => {
  mainDisplay = `${mainDisplay}` + `${HTMLElement.innerHTML}`;
  finalDisplay.innerHTML = `${mainDisplay}`;
  subDisplay = `${subDisplay}` + `${HTMLElement.innerHTML}`;
  workingDisplay.innerHTML = `${subDisplay}`;
};

for (let i = 0; i < number.length; i++) {
  number[i].addEventListener("click", () => {
    updateDisplay(number[i]);
  });
}

// ==========================
// ====decimal and minus=====
// ==========================

key__decimal.addEventListener("click", () => {
  // I HAVE ALSO NEGATED THE IF SO IT WILL DO THIS IF THERE ISN'T A "."
  if (!mainDisplay.includes(".")) {
    updateDisplay(key__decimal);
  }
});
```
